/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LayoutRouteRouteImport } from './routes/_layout/route'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as PageLockScreenIndexRouteImport } from './routes/_page/lock-screen/index'
import { Route as LayoutToDoListIndexRouteImport } from './routes/_layout/to-do-list/index'
import { Route as LayoutTaskManagementIndexRouteImport } from './routes/_layout/task-management/index'
import { Route as LayoutChatIndexRouteImport } from './routes/_layout/chat/index'
import { Route as PageResetResetCoverIndexRouteImport } from './routes/_page/_reset/reset-cover/index'
import { Route as PageResetResetBasicIndexRouteImport } from './routes/_page/_reset/reset-basic/index'
import { Route as PageRegisterRegisterCoverIndexRouteImport } from './routes/_page/_register/register-cover/index'
import { Route as PageRegisterRegisterBasicIndexRouteImport } from './routes/_page/_register/register-basic/index'
import { Route as PageLoginLoginCoverIndexRouteImport } from './routes/_page/_login/login-cover/index'
import { Route as PageLoginLoginBasicIndexRouteImport } from './routes/_page/_login/login-basic/index'
import { Route as PageForgotPasswordForgotPasswordCoverIndexRouteImport } from './routes/_page/_forgot-password/forgotPassword-cover/index'
import { Route as PageForgotPasswordForgotPasswordBasicIndexRouteImport } from './routes/_page/_forgot-password/forgotPassword-basic/index'
import { Route as PageEmailVerificationEmailVerificationCoverIndexRouteImport } from './routes/_page/_email-verification/emailVerification-cover/index'
import { Route as PageEmailVerificationEmailVerificationBasicIndexRouteImport } from './routes/_page/_email-verification/emailVerification-basic/index'

const LayoutRouteRoute = LayoutRouteRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const PageLockScreenIndexRoute = PageLockScreenIndexRouteImport.update({
  id: '/_page/lock-screen/',
  path: '/lock-screen/',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutToDoListIndexRoute = LayoutToDoListIndexRouteImport.update({
  id: '/to-do-list/',
  path: '/to-do-list/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const LayoutTaskManagementIndexRoute =
  LayoutTaskManagementIndexRouteImport.update({
    id: '/task-management/',
    path: '/task-management/',
    getParentRoute: () => LayoutRouteRoute,
  } as any)
const LayoutChatIndexRoute = LayoutChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => LayoutRouteRoute,
} as any)
const PageResetResetCoverIndexRoute =
  PageResetResetCoverIndexRouteImport.update({
    id: '/_page/_reset/reset-cover/',
    path: '/reset-cover/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageResetResetBasicIndexRoute =
  PageResetResetBasicIndexRouteImport.update({
    id: '/_page/_reset/reset-basic/',
    path: '/reset-basic/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageRegisterRegisterCoverIndexRoute =
  PageRegisterRegisterCoverIndexRouteImport.update({
    id: '/_page/_register/register-cover/',
    path: '/register-cover/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageRegisterRegisterBasicIndexRoute =
  PageRegisterRegisterBasicIndexRouteImport.update({
    id: '/_page/_register/register-basic/',
    path: '/register-basic/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageLoginLoginCoverIndexRoute =
  PageLoginLoginCoverIndexRouteImport.update({
    id: '/_page/_login/login-cover/',
    path: '/login-cover/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageLoginLoginBasicIndexRoute =
  PageLoginLoginBasicIndexRouteImport.update({
    id: '/_page/_login/login-basic/',
    path: '/login-basic/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageForgotPasswordForgotPasswordCoverIndexRoute =
  PageForgotPasswordForgotPasswordCoverIndexRouteImport.update({
    id: '/_page/_forgot-password/forgotPassword-cover/',
    path: '/forgotPassword-cover/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageForgotPasswordForgotPasswordBasicIndexRoute =
  PageForgotPasswordForgotPasswordBasicIndexRouteImport.update({
    id: '/_page/_forgot-password/forgotPassword-basic/',
    path: '/forgotPassword-basic/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageEmailVerificationEmailVerificationCoverIndexRoute =
  PageEmailVerificationEmailVerificationCoverIndexRouteImport.update({
    id: '/_page/_email-verification/emailVerification-cover/',
    path: '/emailVerification-cover/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PageEmailVerificationEmailVerificationBasicIndexRoute =
  PageEmailVerificationEmailVerificationBasicIndexRouteImport.update({
    id: '/_page/_email-verification/emailVerification-basic/',
    path: '/emailVerification-basic/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof LayoutIndexRoute
  '/chat/': typeof LayoutChatIndexRoute
  '/task-management/': typeof LayoutTaskManagementIndexRoute
  '/to-do-list/': typeof LayoutToDoListIndexRoute
  '/lock-screen/': typeof PageLockScreenIndexRoute
  '/emailVerification-basic/': typeof PageEmailVerificationEmailVerificationBasicIndexRoute
  '/emailVerification-cover/': typeof PageEmailVerificationEmailVerificationCoverIndexRoute
  '/forgotPassword-basic/': typeof PageForgotPasswordForgotPasswordBasicIndexRoute
  '/forgotPassword-cover/': typeof PageForgotPasswordForgotPasswordCoverIndexRoute
  '/login-basic/': typeof PageLoginLoginBasicIndexRoute
  '/login-cover/': typeof PageLoginLoginCoverIndexRoute
  '/register-basic/': typeof PageRegisterRegisterBasicIndexRoute
  '/register-cover/': typeof PageRegisterRegisterCoverIndexRoute
  '/reset-basic/': typeof PageResetResetBasicIndexRoute
  '/reset-cover/': typeof PageResetResetCoverIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof LayoutIndexRoute
  '/chat': typeof LayoutChatIndexRoute
  '/task-management': typeof LayoutTaskManagementIndexRoute
  '/to-do-list': typeof LayoutToDoListIndexRoute
  '/lock-screen': typeof PageLockScreenIndexRoute
  '/emailVerification-basic': typeof PageEmailVerificationEmailVerificationBasicIndexRoute
  '/emailVerification-cover': typeof PageEmailVerificationEmailVerificationCoverIndexRoute
  '/forgotPassword-basic': typeof PageForgotPasswordForgotPasswordBasicIndexRoute
  '/forgotPassword-cover': typeof PageForgotPasswordForgotPasswordCoverIndexRoute
  '/login-basic': typeof PageLoginLoginBasicIndexRoute
  '/login-cover': typeof PageLoginLoginCoverIndexRoute
  '/register-basic': typeof PageRegisterRegisterBasicIndexRoute
  '/register-cover': typeof PageRegisterRegisterCoverIndexRoute
  '/reset-basic': typeof PageResetResetBasicIndexRoute
  '/reset-cover': typeof PageResetResetCoverIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteRouteWithChildren
  '/_layout/': typeof LayoutIndexRoute
  '/_layout/chat/': typeof LayoutChatIndexRoute
  '/_layout/task-management/': typeof LayoutTaskManagementIndexRoute
  '/_layout/to-do-list/': typeof LayoutToDoListIndexRoute
  '/_page/lock-screen/': typeof PageLockScreenIndexRoute
  '/_page/_email-verification/emailVerification-basic/': typeof PageEmailVerificationEmailVerificationBasicIndexRoute
  '/_page/_email-verification/emailVerification-cover/': typeof PageEmailVerificationEmailVerificationCoverIndexRoute
  '/_page/_forgot-password/forgotPassword-basic/': typeof PageForgotPasswordForgotPasswordBasicIndexRoute
  '/_page/_forgot-password/forgotPassword-cover/': typeof PageForgotPasswordForgotPasswordCoverIndexRoute
  '/_page/_login/login-basic/': typeof PageLoginLoginBasicIndexRoute
  '/_page/_login/login-cover/': typeof PageLoginLoginCoverIndexRoute
  '/_page/_register/register-basic/': typeof PageRegisterRegisterBasicIndexRoute
  '/_page/_register/register-cover/': typeof PageRegisterRegisterCoverIndexRoute
  '/_page/_reset/reset-basic/': typeof PageResetResetBasicIndexRoute
  '/_page/_reset/reset-cover/': typeof PageResetResetCoverIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat/'
    | '/task-management/'
    | '/to-do-list/'
    | '/lock-screen/'
    | '/emailVerification-basic/'
    | '/emailVerification-cover/'
    | '/forgotPassword-basic/'
    | '/forgotPassword-cover/'
    | '/login-basic/'
    | '/login-cover/'
    | '/register-basic/'
    | '/register-cover/'
    | '/reset-basic/'
    | '/reset-cover/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/task-management'
    | '/to-do-list'
    | '/lock-screen'
    | '/emailVerification-basic'
    | '/emailVerification-cover'
    | '/forgotPassword-basic'
    | '/forgotPassword-cover'
    | '/login-basic'
    | '/login-cover'
    | '/register-basic'
    | '/register-cover'
    | '/reset-basic'
    | '/reset-cover'
  id:
    | '__root__'
    | '/_layout'
    | '/_layout/'
    | '/_layout/chat/'
    | '/_layout/task-management/'
    | '/_layout/to-do-list/'
    | '/_page/lock-screen/'
    | '/_page/_email-verification/emailVerification-basic/'
    | '/_page/_email-verification/emailVerification-cover/'
    | '/_page/_forgot-password/forgotPassword-basic/'
    | '/_page/_forgot-password/forgotPassword-cover/'
    | '/_page/_login/login-basic/'
    | '/_page/_login/login-cover/'
    | '/_page/_register/register-basic/'
    | '/_page/_register/register-cover/'
    | '/_page/_reset/reset-basic/'
    | '/_page/_reset/reset-cover/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRouteRoute: typeof LayoutRouteRouteWithChildren
  PageLockScreenIndexRoute: typeof PageLockScreenIndexRoute
  PageEmailVerificationEmailVerificationBasicIndexRoute: typeof PageEmailVerificationEmailVerificationBasicIndexRoute
  PageEmailVerificationEmailVerificationCoverIndexRoute: typeof PageEmailVerificationEmailVerificationCoverIndexRoute
  PageForgotPasswordForgotPasswordBasicIndexRoute: typeof PageForgotPasswordForgotPasswordBasicIndexRoute
  PageForgotPasswordForgotPasswordCoverIndexRoute: typeof PageForgotPasswordForgotPasswordCoverIndexRoute
  PageLoginLoginBasicIndexRoute: typeof PageLoginLoginBasicIndexRoute
  PageLoginLoginCoverIndexRoute: typeof PageLoginLoginCoverIndexRoute
  PageRegisterRegisterBasicIndexRoute: typeof PageRegisterRegisterBasicIndexRoute
  PageRegisterRegisterCoverIndexRoute: typeof PageRegisterRegisterCoverIndexRoute
  PageResetResetBasicIndexRoute: typeof PageResetResetBasicIndexRoute
  PageResetResetCoverIndexRoute: typeof PageResetResetCoverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof LayoutRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_page/lock-screen/': {
      id: '/_page/lock-screen/'
      path: '/lock-screen'
      fullPath: '/lock-screen/'
      preLoaderRoute: typeof PageLockScreenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/to-do-list/': {
      id: '/_layout/to-do-list/'
      path: '/to-do-list'
      fullPath: '/to-do-list/'
      preLoaderRoute: typeof LayoutToDoListIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/task-management/': {
      id: '/_layout/task-management/'
      path: '/task-management'
      fullPath: '/task-management/'
      preLoaderRoute: typeof LayoutTaskManagementIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_layout/chat/': {
      id: '/_layout/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof LayoutChatIndexRouteImport
      parentRoute: typeof LayoutRouteRoute
    }
    '/_page/_reset/reset-cover/': {
      id: '/_page/_reset/reset-cover/'
      path: '/reset-cover'
      fullPath: '/reset-cover/'
      preLoaderRoute: typeof PageResetResetCoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_reset/reset-basic/': {
      id: '/_page/_reset/reset-basic/'
      path: '/reset-basic'
      fullPath: '/reset-basic/'
      preLoaderRoute: typeof PageResetResetBasicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_register/register-cover/': {
      id: '/_page/_register/register-cover/'
      path: '/register-cover'
      fullPath: '/register-cover/'
      preLoaderRoute: typeof PageRegisterRegisterCoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_register/register-basic/': {
      id: '/_page/_register/register-basic/'
      path: '/register-basic'
      fullPath: '/register-basic/'
      preLoaderRoute: typeof PageRegisterRegisterBasicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_login/login-cover/': {
      id: '/_page/_login/login-cover/'
      path: '/login-cover'
      fullPath: '/login-cover/'
      preLoaderRoute: typeof PageLoginLoginCoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_login/login-basic/': {
      id: '/_page/_login/login-basic/'
      path: '/login-basic'
      fullPath: '/login-basic/'
      preLoaderRoute: typeof PageLoginLoginBasicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_forgot-password/forgotPassword-cover/': {
      id: '/_page/_forgot-password/forgotPassword-cover/'
      path: '/forgotPassword-cover'
      fullPath: '/forgotPassword-cover/'
      preLoaderRoute: typeof PageForgotPasswordForgotPasswordCoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_forgot-password/forgotPassword-basic/': {
      id: '/_page/_forgot-password/forgotPassword-basic/'
      path: '/forgotPassword-basic'
      fullPath: '/forgotPassword-basic/'
      preLoaderRoute: typeof PageForgotPasswordForgotPasswordBasicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_email-verification/emailVerification-cover/': {
      id: '/_page/_email-verification/emailVerification-cover/'
      path: '/emailVerification-cover'
      fullPath: '/emailVerification-cover/'
      preLoaderRoute: typeof PageEmailVerificationEmailVerificationCoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_page/_email-verification/emailVerification-basic/': {
      id: '/_page/_email-verification/emailVerification-basic/'
      path: '/emailVerification-basic'
      fullPath: '/emailVerification-basic/'
      preLoaderRoute: typeof PageEmailVerificationEmailVerificationBasicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LayoutRouteRouteChildren {
  LayoutIndexRoute: typeof LayoutIndexRoute
  LayoutChatIndexRoute: typeof LayoutChatIndexRoute
  LayoutTaskManagementIndexRoute: typeof LayoutTaskManagementIndexRoute
  LayoutToDoListIndexRoute: typeof LayoutToDoListIndexRoute
}

const LayoutRouteRouteChildren: LayoutRouteRouteChildren = {
  LayoutIndexRoute: LayoutIndexRoute,
  LayoutChatIndexRoute: LayoutChatIndexRoute,
  LayoutTaskManagementIndexRoute: LayoutTaskManagementIndexRoute,
  LayoutToDoListIndexRoute: LayoutToDoListIndexRoute,
}

const LayoutRouteRouteWithChildren = LayoutRouteRoute._addFileChildren(
  LayoutRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  LayoutRouteRoute: LayoutRouteRouteWithChildren,
  PageLockScreenIndexRoute: PageLockScreenIndexRoute,
  PageEmailVerificationEmailVerificationBasicIndexRoute:
    PageEmailVerificationEmailVerificationBasicIndexRoute,
  PageEmailVerificationEmailVerificationCoverIndexRoute:
    PageEmailVerificationEmailVerificationCoverIndexRoute,
  PageForgotPasswordForgotPasswordBasicIndexRoute:
    PageForgotPasswordForgotPasswordBasicIndexRoute,
  PageForgotPasswordForgotPasswordCoverIndexRoute:
    PageForgotPasswordForgotPasswordCoverIndexRoute,
  PageLoginLoginBasicIndexRoute: PageLoginLoginBasicIndexRoute,
  PageLoginLoginCoverIndexRoute: PageLoginLoginCoverIndexRoute,
  PageRegisterRegisterBasicIndexRoute: PageRegisterRegisterBasicIndexRoute,
  PageRegisterRegisterCoverIndexRoute: PageRegisterRegisterCoverIndexRoute,
  PageResetResetBasicIndexRoute: PageResetResetBasicIndexRoute,
  PageResetResetCoverIndexRoute: PageResetResetCoverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
